config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    post 'comments' => 'comments#create'
    resources :answers do
      post 'comments' => 'comments#create'
    end
  end
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  post '/questions/:question_id/answers/:answer_id/votes' => 'votes#create'
  post 'questions/:id/votes' => 'votes#create'
  post '/questions/:question_id/answers/:answer_id/comment/:comment_id/votes' => 'votes#create'
  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :questions
  has_many :answers
  has_many :votes
  has_many :comments
  validates :username, :email, :password_digest, presence: true
  validates :username, :email, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:new, :create]

  def new
    @user = User.new
    render :new, layout: false
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        set_session
        format.html { redirect_to @user, notice: 'User Created' }
        format.json { render :user, status: :created, location: @user }
      else
        format.html { redirect_to :new_user }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User Updated' }
        format.json { render :show, status: :updated, location: @user }
      else
        format.html { redirect to :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    session.clear if @user == current_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to login }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end


end

app/views/users/_form.html.erb
<div class="overlay">
  <div class="content-wrapper">
    <div class="form-content">
      <a class="close"><img class="close" src="/assets/small_shaq.png"></a>
      <%= form_for @user do |f| %>
      <%= f.label(:username, 'Username') %>
      <%= f.text_field(:username) %>
      <%= f.label(:email, 'Email') %>
      <%= f.text_field(:email) %>
      <%= f.label(:password, 'Password') %>
      <%= f.password_field(:password) %>
      <%= f.submit %>
      <% end %>
      <img id="laying-down" src="/assets/shaq_laying_down.jpg" alt="shaq">
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1> Edit User </h>
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="welcome-user">Welcome, <%= @user.username %></h1>

<div class="user-page-questions">
<% if @user.questions.count > 0 %>
  <h3>Here are all of your questions:</h3>
  <% @user.questions.each do |question| %>
    Votes: | <%= question.votes.count %>
    Answers: | <%= question.answers.count %>
      <p><%= link_to("#{question.title}", question_path(question)) %></p>
  <% end %>
<% else %>
  <p>Post a question and you can monitor it's activity here!</p>
  <% end %>
</div>