config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    post 'comments' => 'comments#create'
    resources :answers do
      post 'comments' => 'comments#create'
    end
  end
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  post '/questions/:question_id/answers/:answer_id/votes' => 'votes#create'
  post 'questions/:id/votes' => 'votes#create'
  post '/questions/:question_id/answers/:answer_id/comment/:comment_id/votes' => 'votes#create'
  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShaqOverflow</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <!-- <link href="http://d2v52k3cl9vedd.cloudfront.net/basscss/5.0.0/basscss.min.css" rel="stylesheet"> -->
  <!-- <link rel="stylesheet" type="text/css" href="base.css"> -->
  <!-- <link rel="stylesheet" type="text/css" href="font.css"> -->
  <!-- <link href='http://fonts.googleapis.com/css?family=Josefin+Sans|Lobster' rel='stylesheet' type='text/css'> -->
  <%= csrf_meta_tags %>
</head>

<body>
<div class="clearfix black" id="nav-bar">
    <div class="sm-col">
      <img src="http://static.giantbomb.com/uploads/original/1/13641/2182953-shaq.jpg"/>
      <%= link_to 'Shaq Overflow', questions_path, id: "title", class: "button py2 button-transparent" %>
    </div>
    <div class="sm-col-right">
      <div id="shaq-height"></div>
      <%= link_to 'Questions', questions_path, id: "questions-btn", class: "button py2 button-transparent" %>
      <% if current_user %>
      <%= link_to 'Profile', "/users/#{current_user.id}", class: "button py2 button-transparent" %>
      <%= link_to 'Add Question', new_question_path, class: "button py2 button-transparent add-question" %>
      <%= link_to 'Logout', logout_path, id: "logout-btn", class: "button py2 button-transparent" %>
      <% else %>
      <%= link_to 'Login', login_path, class: "button py2 button-transparent login-btn" %>
      <%= link_to 'Signup', new_user_path, id: "signup-btn", class: "button py2 button-transparent" %>
      <% end %>
    </div>
</div>
<div id="main">

  <%= yield %>

</div>

</body>
</html>